{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='watchOperation', url='', help='"A WatchOperation creates Operations when watched resources change."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of WatchOperation', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'ops.crossplane.io/v1alpha1',
    kind: 'WatchOperation',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"WatchOperationSpec specifies the desired state of a WatchOperation."'),
  spec: {
    '#operationTemplate':: d.obj(help='"OperationTemplate is the template for the Operation to be created."'),
    operationTemplate: {
      '#spec':: d.obj(help='"Spec is the specification of the Operation to be created."'),
      spec: {
        '#pipeline':: d.obj(help='"Pipeline is a list of operation function steps that will be used when\\nthis operation runs."'),
        pipeline: {
          '#credentials':: d.obj(help='"Credentials are optional credentials that the operation function needs."'),
          credentials: {
            '#secretRef':: d.obj(help='"A SecretRef is a reference to a secret containing credentials that should\\nbe supplied to the function."'),
            secretRef: {
              '#withName':: d.fn(help='"Name of the secret."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { secretRef+: { name: name } },
              '#withNamespace':: d.fn(help='"Namespace of the secret."', args=[d.arg(name='namespace', type=d.T.string)]),
              withNamespace(namespace): { secretRef+: { namespace: namespace } },
            },
            '#withName':: d.fn(help='"Name of this set of credentials."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { name: name },
            '#withSource':: d.fn(help='"Source of the function credentials."', args=[d.arg(name='source', type=d.T.string)]),
            withSource(source): { source: source },
          },
          '#functionRef':: d.obj(help='"FunctionRef is a reference to the function this step should\\nexecute."'),
          functionRef: {
            '#withName':: d.fn(help='"Name of the referenced function."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { functionRef+: { name: name } },
          },
          '#requirements':: d.obj(help='"Requirements are resource requirements that will be satisfied before\\nthis pipeline step is called for the first time. This allows\\npre-populating required resources without requiring a function to\\nrequest them first."'),
          requirements: {
            '#requiredResources':: d.obj(help='"RequiredResources that will be fetched before this pipeline step\\nis called for the first time."'),
            requiredResources: {
              '#withApiVersion':: d.fn(help='"APIVersion of resources to select."', args=[d.arg(name='apiVersion', type=d.T.string)]),
              withApiVersion(apiVersion): { apiVersion: apiVersion },
              '#withKind':: d.fn(help='"Kind of resources to select."', args=[d.arg(name='kind', type=d.T.string)]),
              withKind(kind): { kind: kind },
              '#withMatchLabels':: d.fn(help='"MatchLabels matches resources by label selector. Only one of Name or\\nMatchLabels may be specified."', args=[d.arg(name='matchLabels', type=d.T.object)]),
              withMatchLabels(matchLabels): { matchLabels: matchLabels },
              '#withMatchLabelsMixin':: d.fn(help='"MatchLabels matches resources by label selector. Only one of Name or\\nMatchLabels may be specified."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
              withMatchLabelsMixin(matchLabels): { matchLabels+: matchLabels },
              '#withName':: d.fn(help='"Name matches a single resource by name. Only one of Name or\\nMatchLabels may be specified."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { name: name },
              '#withNamespace':: d.fn(help='"Namespace to search for resources. Optional for cluster-scoped resources."', args=[d.arg(name='namespace', type=d.T.string)]),
              withNamespace(namespace): { namespace: namespace },
              '#withRequirementName':: d.fn(help='"RequirementName uniquely identifies this group of resources.\\nThis name will be used as the key in RunFunctionRequest.required_resources."', args=[d.arg(name='requirementName', type=d.T.string)]),
              withRequirementName(requirementName): { requirementName: requirementName },
            },
            '#withRequiredResources':: d.fn(help='"RequiredResources that will be fetched before this pipeline step\\nis called for the first time."', args=[d.arg(name='requiredResources', type=d.T.array)]),
            withRequiredResources(requiredResources): { requirements+: { requiredResources: if std.isArray(v=requiredResources) then requiredResources else [requiredResources] } },
            '#withRequiredResourcesMixin':: d.fn(help='"RequiredResources that will be fetched before this pipeline step\\nis called for the first time."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='requiredResources', type=d.T.array)]),
            withRequiredResourcesMixin(requiredResources): { requirements+: { requiredResources+: if std.isArray(v=requiredResources) then requiredResources else [requiredResources] } },
          },
          '#withCredentials':: d.fn(help='"Credentials are optional credentials that the operation function needs."', args=[d.arg(name='credentials', type=d.T.array)]),
          withCredentials(credentials): { credentials: if std.isArray(v=credentials) then credentials else [credentials] },
          '#withCredentialsMixin':: d.fn(help='"Credentials are optional credentials that the operation function needs."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='credentials', type=d.T.array)]),
          withCredentialsMixin(credentials): { credentials+: if std.isArray(v=credentials) then credentials else [credentials] },
          '#withInput':: d.fn(help="\"Input is an optional, arbitrary Kubernetes resource (i.e. a resource\\nwith an apiVersion and kind) that will be passed to the unction as\\nthe 'input' of its RunFunctionRequest.\"", args=[d.arg(name='input', type=d.T.object)]),
          withInput(input): { input: input },
          '#withInputMixin':: d.fn(help="\"Input is an optional, arbitrary Kubernetes resource (i.e. a resource\\nwith an apiVersion and kind) that will be passed to the unction as\\nthe 'input' of its RunFunctionRequest.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='input', type=d.T.object)]),
          withInputMixin(input): { input+: input },
          '#withStep':: d.fn(help='"Step name. Must be unique within its Pipeline."', args=[d.arg(name='step', type=d.T.string)]),
          withStep(step): { step: step },
        },
        '#withMode':: d.fn(help='"Mode controls what type or \\"mode\\" of operation will be used.\\n\\n\\"Pipeline\\" indicates that an Operation specifies a pipeline of\\nfunctions, each of which is responsible for implementing its logic."', args=[d.arg(name='mode', type=d.T.string)]),
        withMode(mode): { spec+: { operationTemplate+: { spec+: { mode: mode } } } },
        '#withPipeline':: d.fn(help='"Pipeline is a list of operation function steps that will be used when\\nthis operation runs."', args=[d.arg(name='pipeline', type=d.T.array)]),
        withPipeline(pipeline): { spec+: { operationTemplate+: { spec+: { pipeline: if std.isArray(v=pipeline) then pipeline else [pipeline] } } } },
        '#withPipelineMixin':: d.fn(help='"Pipeline is a list of operation function steps that will be used when\\nthis operation runs."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='pipeline', type=d.T.array)]),
        withPipelineMixin(pipeline): { spec+: { operationTemplate+: { spec+: { pipeline+: if std.isArray(v=pipeline) then pipeline else [pipeline] } } } },
        '#withRetryLimit':: d.fn(help='"RetryLimit configures how many times the operation may fail. When the\\nfailure limit is exceeded, the operation will not be retried."', args=[d.arg(name='retryLimit', type=d.T.integer)]),
        withRetryLimit(retryLimit): { spec+: { operationTemplate+: { spec+: { retryLimit: retryLimit } } } },
      },
      '#withMetadata':: d.fn(help='"Standard object metadata."', args=[d.arg(name='metadata', type=d.T.object)]),
      withMetadata(metadata): { spec+: { operationTemplate+: { metadata: metadata } } },
      '#withMetadataMixin':: d.fn(help='"Standard object metadata."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metadata', type=d.T.object)]),
      withMetadataMixin(metadata): { spec+: { operationTemplate+: { metadata+: metadata } } },
    },
    '#watch':: d.obj(help='"Watch specifies the resource to watch."'),
    watch: {
      '#withApiVersion':: d.fn(help='"APIVersion of the resource to watch."', args=[d.arg(name='apiVersion', type=d.T.string)]),
      withApiVersion(apiVersion): { spec+: { watch+: { apiVersion: apiVersion } } },
      '#withKind':: d.fn(help='"Kind of the resource to watch."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { spec+: { watch+: { kind: kind } } },
      '#withMatchLabels':: d.fn(help='"MatchLabels selects resources by label. If empty, all resources of the\\nspecified kind are watched."', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabels(matchLabels): { spec+: { watch+: { matchLabels: matchLabels } } },
      '#withMatchLabelsMixin':: d.fn(help='"MatchLabels selects resources by label. If empty, all resources of the\\nspecified kind are watched."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchLabels', type=d.T.object)]),
      withMatchLabelsMixin(matchLabels): { spec+: { watch+: { matchLabels+: matchLabels } } },
      '#withNamespace':: d.fn(help='"Namespace selects resources in a specific namespace. If empty, all\\nnamespaces are watched. Only applicable for namespaced resources."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { watch+: { namespace: namespace } } },
    },
    '#withConcurrencyPolicy':: d.fn(help='"ConcurrencyPolicy specifies how to treat concurrent executions of an\\noperation."', args=[d.arg(name='concurrencyPolicy', type=d.T.string)]),
    withConcurrencyPolicy(concurrencyPolicy): { spec+: { concurrencyPolicy: concurrencyPolicy } },
    '#withFailedHistoryLimit':: d.fn(help='"FailedHistoryLimit is the number of failed Operations to retain."', args=[d.arg(name='failedHistoryLimit', type=d.T.integer)]),
    withFailedHistoryLimit(failedHistoryLimit): { spec+: { failedHistoryLimit: failedHistoryLimit } },
    '#withSuccessfulHistoryLimit':: d.fn(help='"SuccessfulHistoryLimit is the number of successful Operations to retain."', args=[d.arg(name='successfulHistoryLimit', type=d.T.integer)]),
    withSuccessfulHistoryLimit(successfulHistoryLimit): { spec+: { successfulHistoryLimit: successfulHistoryLimit } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
